version: '3.8'

services:
  redpanda:
    image: redpandadata/redpanda:latest
    command:
      - redpanda start --overprovisioned --smp 1 --memory 1G --reserve-memory 0M --node-id 0 --check=false
      - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
    ports:
      - "9092:9092"
    networks:
      - app-network

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: hw
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-network

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow
    ports:
      - "5000:5000"
    command: mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root /artifacts --host 0.0.0.0
    networks:
      - app-network

  app:
    build: .
    ports:
      - "8003:8003"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/hw
      - KAFKA_BOOTSTRAP_SERVERS=redpanda:29092
      - REDIS_HOST=redis
      - USE_MLFLOW=true
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - postgres
      - redpanda
      - redis
      - mlflow
    networks:
      - app-network

  worker:
    build: .
    command: python workers/moderation_worker.py
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/hw
      - KAFKA_BOOTSTRAP_SERVERS=redpanda:29092
    depends_on:
      - app
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - app-network

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    networks:
      - app-network

  console:
    image: redpandadata/console:latest
    environment:
      KAFKA_BROKERS: redpanda:29092
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pg_data: